rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-19mode
branches:
  only:
    - master
script: bundle exec rspec
addons:
  code_climate:
    repo_token: 3dd24352e8b43b740fbd7af43228206759842fafd86ce253b1062d213338a1a2
gemfile: Gemfile.travis
sudo: false
language: ruby
cache: bundler
