rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.3.0
  - jruby-19mode
branches:
  only:
    - master
script: bundle exec rspec
addons:
  code_climate:
    repo_token: 3dd24352e8b43b740fbd7af43228206759842fafd86ce253b1062d213338a1a2
gemfile: Gemfile.travis
sudo: false
language: ruby
